# Generated by Django 2.0 on 2017-12-07 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 14, 29, 14, 766982, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qqs', to='polls.Question'),
        ),
    ]
